import { chromium } from 'playwright';
import fs from 'node:fs';
fs.mkdirSync('.qa', { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:3850/', { waitUntil: 'networkidle' });
const sec = page.locator('#parla');
await sec.scrollIntoViewIfNeeded();
await page.waitForTimeout(1500);
await page.screenshot({ path: '.qa/core-idle.png' });
console.log('core hint:', await sec.getByText('TOCCATE IL NUCLEO').isVisible());
// thinking state via a question
await sec.getByRole('button', { name: 'Come funziona DOLMIR?' }).click();
await page.waitForTimeout(1600);
await page.screenshot({ path: '.qa/core-thinking.png' });
const m = await page.newPage ? 0 : 0;
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
console.log('overflow:', overflow);
await page.close();
const mp = await browser.newPage({ viewport: { width: 390, height: 844 } });
await mp.goto('http://localhost:3850/', { waitUntil: 'networkidle' });
await mp.locator('#parla').scrollIntoViewIfNeeded();
await mp.waitForTimeout(900);
await mp.screenshot({ path: '.qa/core-390.png' });
console.log('390 overflow:', await mp.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await browser.close();
